server:
  port: 9090


# dubbo 配置
dubbo:
  application:
    id: dubbo-pay-consumer
    name: dubbo-pay-consumer
  registry:
    address: zookeeper://192.168.191.128:2181,192.168.191.129:2181,192.168.191.130:2181,192.168.191.131:2181?init.timeout=60000
    group: shop
    timeout: 50000
  protocol:
    name: dubbo
    port: 20886



