server:
  port: 8084


# dubbo 配置
dubbo:
  application:
    id: dubbo-order-consumer
    name: dubbo-order-consumer
  registry:
    address: zookeeper://192.168.191.128:2181,192.168.191.129:2181,192.168.191.130:2181,192.168.191.131:2181?init.timeout=60000
    group: shop
    timeout: 50000
  protocol:
    name: dubbo
    port: 20884

#order:
#  port: 8084

#shop:
#  order:
#    baseURI: ${server.host}:${server.port}${server.servlet.context-path}
#    confirm: /order/confirm